### ISSUE TITLE
ZSTDCompress function error: uncaughtException: Command failed: Incorrect parameters

### ISSUE THREAD

**Issue by Dhvani-Katkoria** [Stieneee/simple-zstd#1]
I am facing error while using function ZSTDCompress function for compression of stream data to compressed buffer.

Node Version: 10.16.0
Npm Version: 6.9.0
OS: Ubuntu 18.04

What can be the solution to resolve this error?

Following are the error logs :

`error: uncaughtException: Command failed: Incorrect parameters
Usage : 
      zstd [args] [FILE(s)] [-o file] 

FILE    : a filename 
          with no FILE, or when FILE is - , read standard input
Arguments : 
 -#     : # compression level (1-19, default:3) 
 -d     : decompression 
 -D file: use `file` as Dictionary 
 -o file: result stored into `file` (only if 1 input file) 
 -f     : overwrite output without prompting and (de)compress links 
--rm    : remove source file(s) after successful de/compression 
 -k     : preserve source file(s) (default) 
 -h/-H  : display help/long help and exit 
 
{ date: 'Thu Jul 18 2019 11:00:01 GMT+0530 (India Standard Time)',
  process:
   { pid: 8622,
     uid: 0,
     gid: 0,
     cwd: '/home/gdmtrunk',
     execPath: '/usr/local/bin/node',
     version: 'v10.16.0',
     argv:
      [ '/usr/local/bin/node',
        '/home/gdmtrunk/server.js' ],
     memoryUsage:
      { rss: 170455040,
        heapTotal: 129097728,
        heapUsed: 112122016,
        external: 72180011 } },
  os:
   { loadavg: [ 1.04345703125, 1.24267578125, 1.625 ],
     uptime: 2035 },
  trace:
   [ { column: 12,
       file:
        '/home/gdmtrunk/node_modules/duplex-child-process/index.js',
       function: 'ChildProcess.onExit',
       line: 116,
       method: 'onExit',
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'Object.onceWrapper',
       line: 286,
       method: 'onceWrapper',
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'ChildProcess.emit',
       line: 198,
       method: 'emit',
       native: false },
     { column: 20,
       file: 'domain.js',
       function: 'ChildProcess.EventEmitter.emit',
       line: 448,
       method: 'emit',
       native: false },
     { column: 16,
       file: 'internal/child_process.js',
       function: 'maybeClose',
       line: 982,
       method: null,
       native: false },
     { column: 11,
       file: 'internal/child_process.js',
       function: 'Socket.stream.socket.on',
       line: 389,
       method: 'on',
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'Socket.emit',
       line: 198,
       method: 'emit',
       native: false },
     { column: 20,
       file: 'domain.js',
       function: 'Socket.EventEmitter.emit',
       line: 448,
       method: 'emit',
       native: false },
     { column: 12,
       file: 'net.js',
       function: 'Pipe._handle.close',
       line: 606,
       method: 'close',
       native: false } ],
  stack:
   [ 'Error: Command failed: Incorrect parameters',
     'Usage : ',
     '      zstd [args] [FILE(s)] [-o file] ',
     '',
     'FILE    : a filename ',
     '          with no FILE, or when FILE is - , read standard input',
     'Arguments : ',
     ' -#     : # compression level (1-19, default:3) ',
     ' -d     : decompression ',
     ' -D file: use `file` as Dictionary ',
     ' -o file: result stored into `file` (only if 1 input file) ',
     ' -f     : overwrite output without prompting and (de)compress links ',
     '--rm    : remove source file(s) after successful de/compression ',
     ' -k     : preserve source file(s) (default) ',
     ' -h/-H  : display help/long help and exit ',
     '',
     '    at ChildProcess.onExit (/home/gdmtrunk/node_modules/duplex-child-process/index.js:116:12)',
     '    at Object.onceWrapper (events.js:286:20)',
     '    at ChildProcess.emit (events.js:198:13)',
     '    at ChildProcess.EventEmitter.emit (domain.js:448:20)',
     '    at maybeClose (internal/child_process.js:982:16)',
     '    at Socket.stream.socket.on (internal/child_process.js:389:11)',
     '    at Socket.emit (events.js:198:13)',
     '    at Socket.EventEmitter.emit (domain.js:448:20)',
     '    at Pipe._handle.close (net.js:606:12)' ] }
18 Jul 11:00:01 - [red] Uncaught Exception:
18 Jul 11:00:01 - Error: Command failed: Incorrect parameters
Usage : 
      zstd [args] [FILE(s)] [-o file] 

FILE    : a filename 
          with no FILE, or when FILE is - , read standard input
Arguments : 
 -#     : # compression level (1-19, default:3) 
 -d     : decompression 
 -D file: use `file` as Dictionary 
 -o file: result stored into `file` (only if 1 input file) 
 -f     : overwrite output without prompting and (de)compress links 
--rm    : remove source file(s) after successful de/compression 
 -k     : preserve source file(s) (default) 
 -h/-H  : display help/long help and exit 

    at ChildProcess.onExit (/home/gdmtrunk/node_modules/duplex-child-process/index.js:116:12)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at Pipe._handle.close (net.js:606:12)`

**Comment by Stieneee** [comment]
My apologies on the delay. I wasn't aware that Github didn't subscribe me to these issues. 

Can you provide a code sample?

**Comment by Stieneee** [comment]
Closing due to lack of information.
